[WIP] Add build image (#11)
* Add build image

* Fix wrong indentation in Makefile

diff --git a/Dockerfiles/build/assets/bin/oc_clone b/Dockerfiles/build/assets/bin/oc_clone
--- a/Dockerfiles/build/assets/bin/oc_clone
+++ b/Dockerfiles/build/assets/bin/oc_clone
@@ -1,3 +1,5 @@
+#!/bin/sh
+#
 # Copyright 2016 The WWU eLectures Team All rights reserved.
 #
 # Licensed under the Educational Community License, Version 2.0
@@ -12,13 +14,13 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
+set -e
 
-DOCKERFILES="${BASEDIR}/Dockerfiles"
-DOCKERFILES_ADMIN="${DOCKERFILES}/admin"
-DOCKERFILES_ADMINWORKER="${DOCKERFILES}/adminworker"
-DOCKERFILES_ALLINONE="${DOCKERFILES}/allinone"
-DOCKERFILES_INGEST="${DOCKERFILES}/ingest"
-DOCKERFILES_PRESENTATION="${DOCKERFILES}/presentation"
-DOCKERFILES_WORKER="${DOCKERFILES}/worker"
-DOCKERFILES_BUILD="${DOCKERFILES}/build"
+if is_git_repo; then
+  log_err "oc_clone" "You are already in a Git repository. Cannot clone here."
+  exit 1
+fi
+
+cd "${OPENCAST_SRC}"
+git clone "${OPENCAST_URL}" .
+git checkout "${OPENCAST_VERSION}"
